import type { PlacementScreenActions, PlacementScreenModel } from './dailyLearningPresentation';

interface PlacementScreenProps { readonly model: PlacementScreenModel; readonly actions: PlacementScreenActions }

const buttonClass = 'min-h-11 rounded-xl border border-[var(--sf-border)] bg-[var(--sf-surface)] px-4 py-2 font-bold text-[var(--sf-text)] transition-colors hover:border-[var(--sf-brand)] focus-visible:outline-2 focus-visible:outline-offset-2 disabled:opacity-50 motion-reduce:transition-none';
const confidenceLabels = { low: 'Low confidence', medium: 'Medium confidence', high: 'High confidence' } as const;

export function PlacementScreen({ model, actions }: PlacementScreenProps) {
  const heading = <h1 id="daily-placement-heading" ref={model.headingRef} tabIndex={-1} className="text-3xl font-black focus-visible:outline-2">Placement check</h1>;
  if (model.status === 'loading') return <section aria-labelledby="daily-placement-heading" aria-busy="true">{heading}<p className="mt-3" role="status" aria-live="polite">{model.message}</p></section>;
  if (model.status === 'intro') return <section aria-labelledby="daily-placement-heading">{heading}<p className="mt-3">{model.message}</p><p className="mt-2 text-sm">{model.eligibleCount} eligible words are available. This check is diagnostic and does not change learning history.</p><div className="mt-5 flex flex-wrap gap-3"><button type="button" onClick={actions.start} className={buttonClass}>Start placement check</button><button type="button" onClick={actions.exit} className={buttonClass}>Back to Today</button></div></section>;
  if (model.status === 'question') return <section aria-labelledby="daily-placement-heading">{heading}<button type="button" onClick={actions.exit} className={`${buttonClass} mt-3`}>Exit placement check</button><div className="mt-4" role="progressbar" aria-label="Placement progress" aria-valuemin={0} aria-valuemax={model.total} aria-valuenow={model.current}>Question {model.current} of {model.total}</div><h2 className="mt-5 text-xl font-black" lang={model.promptLanguage}>{model.prompt}</h2><fieldset className="mt-4"><legend className="font-bold">Choose one answer</legend><div className="mt-3 grid grid-cols-1 gap-3 sm:grid-cols-2">{model.options.map((option) => <button key={option.id} type="button" lang={option.language} aria-pressed={model.selectedId === option.id} onClick={() => actions.chooseAnswer(option.id)} className={buttonClass}>{option.label}</button>)}</div></fieldset><button type="button" disabled={!model.selectedId} onClick={actions.submitAnswer} className={`${buttonClass} mt-5`}>Submit answer</button><p className="sr-only" role="status" aria-live="polite">{model.message}</p></section>;
  if (model.status === 'insufficient') return <section aria-labelledby="daily-placement-heading">{heading}<div className="mt-5 rounded-2xl border border-amber-500 p-5" role="status" aria-live="polite"><h2 className="text-xl font-black">Not enough evidence</h2><p className="mt-2">{model.message}</p><p className="mt-2 font-bold">{model.eligibleCount} of {model.requiredCount} eligible words</p><p className="mt-2 text-sm">No learning path has been inferred.</p></div><div className="mt-5 flex flex-wrap gap-3"><button type="button" onClick={actions.openPaths} className={buttonClass}>Open Paths</button><button type="button" onClick={actions.exit} className={buttonClass}>Back to Today</button></div></section>;
  if (model.status === 'error') return <section aria-labelledby="daily-placement-heading">{heading}<div className="mt-5 rounded-2xl border border-rose-500 p-5" role="alert" aria-live="assertive"><h2 className="text-xl font-black">Placement check needs attention</h2><p className="mt-2">{model.message}</p><button type="button" onClick={actions.retry} className={`${buttonClass} mt-4`}>Try again</button></div></section>;
  return <section aria-labelledby="daily-placement-heading">{heading}<div className="mt-5 rounded-2xl border border-[var(--sf-border)] p-5" role="status" aria-live="polite"><p className="text-sm font-bold text-[var(--sf-brand-text)]">Recommended path</p><h2 className="mt-1 text-2xl font-black">{model.recommendationLabel}</h2><p className="mt-2 font-bold">{confidenceLabels[model.confidence]}</p><p className="mt-2">{model.correctCount} of {model.answeredCount} answered correctly.</p><p className="mt-3">{model.message}</p><p className="mt-3 text-sm text-[var(--sf-text-muted)]">This is a diagnostic guide, not an official exam score. It does not change your review history, mastery, XP, or path access.</p></div><div className="mt-5 flex flex-wrap gap-3"><button type="button" onClick={actions.openPaths} className={buttonClass}>Open Paths</button><button type="button" onClick={actions.exit} className={buttonClass}>Back to Today</button></div></section>;
}

export type { PlacementScreenProps };
