import { renderToStaticMarkup } from 'react-dom/server';
import { describe, expect, it, vi } from 'vitest';
import { LandingPage } from './LandingPage';
import {
  applyLandingQuickStartIntent,
  createLandingQuickStartIntent,
  LANDING_QUICK_START_MAX_LENGTH,
  submitLandingQuickStart,
} from '../navigation/landingQuickStartIntent';
import { createAppViewLocation } from '../navigation/useAppNavigation';

describe('Landing Quick Start', () => {
  it('carries a trimmed Unicode word into the Library draft without generating a card', () => {
    const onQuickStart = vi.fn();
    const submitted = submitLandingQuickStart('  你好 · Serendipity  ', onQuickStart);
    const intent = createLandingQuickStartIntent('  你好 · Serendipity  ');
    const destination = {
      draft: '',
      view: 'landing' as 'landing' | 'library',
      changeDraft(value: string) {
        this.draft = value;
      },
      openLibrary() {
        this.view = 'library';
      },
    };

    expect(submitted).toBe(true);
    expect(onQuickStart).toHaveBeenCalledWith(intent);
    expect(intent).toEqual({
      type: 'landing-quick-start',
      initialDraft: '你好 · Serendipity',
    });
    expect(applyLandingQuickStartIntent(intent, destination)).toBe(true);
    expect(destination).toMatchObject({
      draft: '你好 · Serendipity',
      view: 'library',
    });
    const libraryLocation = createAppViewLocation('/?utm_source=landing', 'library');
    expect(libraryLocation).toBe('/?utm_source=landing&view=library');
    expect(libraryLocation).not.toContain('Serendipity');
  });

  it('does not navigate or dispatch an empty landing submit', () => {
    const onQuickStart = vi.fn();
    const destination = {
      changeDraft: vi.fn(),
      openLibrary: vi.fn(),
    };

    expect(submitLandingQuickStart(' \n\t ', onQuickStart)).toBe(false);
    expect(onQuickStart).not.toHaveBeenCalled();
    expect(applyLandingQuickStartIntent(null, destination)).toBe(false);
    expect(destination.changeDraft).not.toHaveBeenCalled();
    expect(destination.openLibrary).not.toHaveBeenCalled();
  });

  it('accepts the Card Intake boundary and rejects an over-limit draft', () => {
    const onQuickStart = vi.fn();
    const accepted = 'a'.repeat(LANDING_QUICK_START_MAX_LENGTH);
    const rejected = `${accepted}b`;

    expect(createLandingQuickStartIntent(accepted)).toEqual({
      type: 'landing-quick-start',
      initialDraft: accepted,
    });
    expect(createLandingQuickStartIntent(rejected)).toBeNull();
    expect(submitLandingQuickStart(rejected, onQuickStart)).toBe(false);
    expect(onQuickStart).not.toHaveBeenCalled();
  });

  it('renders the empty Quick Start submit as disabled', () => {
    const html = renderToStaticMarkup(
      <LandingPage onEnterApp={vi.fn()} onQuickStart={vi.fn()} />,
    );

    expect(html).toContain('aria-label="Enter word"');
    expect(html).toMatch(/type="submit"[^>]*disabled/);
    expect(html).toMatch(/maxLength="80"|maxlength="80"/);
  });
});

describe('Landing product truth and interaction contracts', () => {
  const renderLanding = () => renderToStaticMarkup(
    <LandingPage onEnterApp={vi.fn()} onQuickStart={vi.fn()} />,
  );

  it('uses implementation-backed copy for images, speech matching, and learning sources', () => {
    const html = renderLanding();

    expect(html).not.toContain('60,000+');
    expect(html).not.toContain('Oxford');
    expect(html).not.toContain('vivid illustrations');
    expect(html).not.toContain('pronunciation accuracy');
    expect(html).not.toContain('Save up to 70%');
    expect(html).not.toContain('vocabulary forever');
    expect(html).not.toContain('permanent long-term');
    expect(html).not.toContain('Instant Cloud Sync');
    expect(html).not.toContain('cognitive science');
    expect(html).not.toContain('instantly across all your devices');
    expect(html).not.toContain('Auto-generated by SonFlash AI');
    expect(html).not.toContain('Build natural speaking reflex and confidence');
    expect(html).not.toContain('Engaging, gamified, and effective');
    expect(html).not.toContain('Unlock Infinite Fluency');
    expect(html).not.toContain('accelerate fluency');
    expect(html).toContain('Example card format preview');
    expect(html).toContain('relevant image cue/search');
    expect(html).toContain('speech/transcript match');
    expect(html).toContain('Compare speech transcripts with target text');
    expect(html).toContain('Vocabulary practice tools');
  });

  it('does not expose an inert speaker control in the sample card', () => {
    const html = renderLanding();
    const sampleCard = html.slice(html.indexOf('Sample Flashcard'), html.indexOf('Ready to elevate'));

    expect(sampleCard).not.toContain('<button');
    expect(sampleCard).toContain('aria-hidden="true"');
  });
});
